services:
  mqtt_client:
    build: .
    container_name: mqtt_client
    restart: unless-stopped
    networks:
      - global-network
    volumes:
      - /app

networks:
  global-network:
    external: true






