services:
  mqtt_client:
    build: .
    container_name: mqtt_client
    networks:
      - global-network
    volumes:
      - /app
    environment:
      - BROKER_ADDRESS=${BROKER_ADDRESS}
      - BROKER_PORT=${BROKER_PORT}
      - BROKER_USERNAME=${BROKER_USERNAME}
      - BROKER_PASSWORD=${BROKER_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}

networks:
  global-network:
    external: true






