services:
  mqtt_client:
    build: .
    container_name: mqtt_client
    restart: unless-stopped
    networks:
      - global-network
    volumes:
      - /app
    environment:
      - BROKER_ADDRESS=${BROKER_ADDRESS}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - DBNAME=${DBNAME}
      - USER=${USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - HOST=${HOST}

networks:
  global-network:
    external: true






