services:
  mqtt_client:
    build: .
    container_name: mqtt_client
    restart: unless-stopped
    networks:
      - global-network
    ports:
      - '5672:5672'
    volumes:
      - /services/mqtt_client:/app

networks:
  global-network:
    external: true






