services:
  mqtt-client:
    container_name: mqtt-client
    image: mqtt-client
    build: .
    networks:
      - global-network
    volumes:
      - /app
    environment:
      - BROKER_ADDRESS=${BROKER_ADDRESS}
      - BROKER_PORT=${BROKER_PORT}
      - BROKER_USERNAME=${BROKER_USERNAME}
      - BROKER_PASSWORD=${BROKER_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - MQTT_TOPIC=${MQTT_TOPIC}

networks:
  global-network:
    external: true